### ISSUE TITLE
it literally doesnt work

### ISSUE THREAD

**Issue by mr-obertson** [OU-Xmen/PAUL#13]

**Comment by mr-obertson** [comment]
main.py is the culprit, sound files are not being loaded properly for some reason. Commenting out the sound stuff makes it run properly, or it can be sidestepped by running the code from settings.py, which opens the main menu with a button press. Checkers and Chess do not work, as well as tetris.

**Comment by mr-obertson** [comment]
Fixed tetris, will reupload in the morning

**Comment by mr-obertson** [comment]
ruled out the possibility of the sound files being corrupted, they still play when loading from settings.py

**Comment by ValNielson** [comment]
only doesn't work for you, rest of team can access PAUL with ease

**Comment by fredxp2003** [comment]
Marking as invalid until more info is discovered.
