### ISSUE TITLE
Asteroids

### ISSUE THREAD

**Issue by fredxp2003** [OU-Xmen/PAUL#15]

**Comment by fredxp2003** [comment]
- [x] Add the 3 variables for main_dir, current_dir, and assets_dir (if all 3 are needed.)
- [x] Fix file loading structure (see #14 )
- [x] Verify everything works in PAUL.

**Comment by fredxp2003** [comment]
This code is not working for #14.  

Affected lines of code:
39-46
319
323

@mr-obertson please update these lines to use `os.path.join`.  Be sure to be doing this on the file-structure-update branch.

**Comment by mr-obertson** [comment]
Resolved the issue
