### ISSUE TITLE
Mad Libs

### ISSUE THREAD

**Issue by fredxp2003** [OU-Xmen/PAUL#21]

**Comment by fredxp2003** [comment]
- [x] Add the 3 variables for main_dir, current_dir, and assets_dir (if all 3 are needed.)
- [x] Fix file loading structure (see #14 )
- [x] Verify everything works in PAUL.

**Comment by fredxp2003** [comment]
`FileNotFoundError: No such file or directory: 'c:\Users\fredi\Documents\GitHub\PAUL\games\MadLibs\assets\paulicon.png'.`

@mr-obertson  please add paulicon.png to the file-structure-update branch.

**Comment by mr-obertson** [comment]
added the file, but the game itself is not being recognized by the new file loader system

**Comment by fredxp2003** [comment]
Problem diagnosed.  Folder needs to be changed to 'Mad Libs', not 'MadLibs'.

**Comment by ValNielson** [comment]
Folder is changed, and still doesn't work, File path will be correct but still won't load. Still diagnosing this is not a Matthew issue, removing matthew from issue

**Comment by mr-obertson** [comment]
problem solved (we think)
